# Generated by Django 5.0.2 on 2024-03-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_postingstore_image_path_array_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': (('manage_blog_posts', 'erlaubt die Verwaltung von Blogposts'),)},
        ),
        migrations.AlterModelOptions(
            name='infopost',
            options={'permissions': (('manage_information_posts', 'erlaubt die Verwaltung von Informationen auf der Startseite'),)},
        ),
    ]
