# Generated by Django 5.0.2 on 2024-03-01 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blogpost_options_alter_infopost_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog Posting'},
        ),
        migrations.AlterModelOptions(
            name='infopost',
            options={'verbose_name': 'Informationspost'},
        ),
        migrations.AlterField(
            model_name='postingstore',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
