# Generated by Django 5.0.3 on 2024-03-06 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blogpost_options_alter_infopost_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_path_array',
            field=models.CharField(default='', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='postingstore',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postingstore',
            name='content_text',
            field=models.TextField(max_length=16384, verbose_name='der Beitrag'),
        ),
        migrations.AlterField(
            model_name='postingstore',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Datum des Beitrags'),
        ),
        migrations.AlterField(
            model_name='postingstore',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='postingstore',
            name='title_image_path',
            field=models.CharField(max_length=512, verbose_name='URL zum Titelbild'),
        ),
    ]
