# Generated by Django 5.0.3 on 2024-03-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='Titel'),
        ),
    ]
