# Generated by Django 5.1 on 2024-09-02 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Blog Posting'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='information',
            field=models.BooleanField(default=False, verbose_name='reiner Informationspost'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='blogbilder', verbose_name='Bild zum Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo1',
            field=models.ImageField(null=True, upload_to='blogbilder', verbose_name='Bild 1 zum Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo2',
            field=models.ImageField(null=True, upload_to='blogbilder', verbose_name='Bild 2 zum Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo3',
            field=models.ImageField(null=True, upload_to='blogbilder', verbose_name='Bild 3 zum Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=16384, verbose_name='der Beitrag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(verbose_name='Datum des Beitrags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Titel'),
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Titel')),
                ('description', models.TextField(max_length=16384, verbose_name='der Beitrag')),
                ('Ort', models.CharField(default='', max_length=128, verbose_name='Ort')),
                ('referenten', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
